### ISSUE TITLE
Extra nesting

### ISSUE THREAD

**Issue by KoziukSerhiy** [IrynaLuchkan/random-quote#2]
https://github.com/IrynaLuchkan/random-quote/blob/6f82af0a3649e2a184ca916a52f7b072bd3d47c8/appXHR.js#L16-L17

fix this use:
`if (xmlhttp.readyState === 4 && xmlhttp.status === 200) `
and check the strict inequality. Like this '==='.

**Comment by IrynaLuchkan** [comment]
Corrected now.
