### ISSUE TITLE
Generate class

### ISSUE THREAD

**Issue by KoziukSerhiy** [IrynaLuchkan/random-quote#3]
Change your code and use ES6 class, try to create independent and reuse class.
https://github.com/IrynaLuchkan/random-quote/blob/master/appXHR.js

**Comment by KoziukSerhiy** [comment]
Напиши ES6 class - "generateQuote", весь функціонал запхай туди а зовні тільки оголоси його та передаай відповідні параметри. 
ПРИКЛАД:
```
class ClassName {
  //...
  // implement your code
};

var className = new ClaccName(someOptions);

//using className and call him methods if necessary.
```
Якщо незнаєш як це зробити то пиши. Я поясню та допоможу.

**Comment by IrynaLuchkan** [comment]
Я намагаюсь пребудувати функціонал, аби впихнути в то клас... і не можу  знайти логіки використання класу. просто впхати в клас функцію, яка викличеться при онклік... чи там щось тре толковіше?

**Comment by IrynaLuchkan** [comment]
File appClass added. Thank you.
